### ISSUE TITLE
BundleRecordingDate as xs:date is limiting

### ISSUE THREAD

**Issue by jblumtritt** [fxru/blam-metadata#16]
IMDI allows values that specify the year, year and month or even Unkown ot Unspecified.
It would be nice to have
yyy
yyy-mm
unkown
in case the exact recording date is not known.

**Comment by fxru** [comment]
What would you suggest? 

I would prefer to require a full date with new submissions, but I see that wth legacy data this is an issue.

However, BundleRecordingDate is not a technical information that is used for anything administrative, so we could loosen the restrictions here and use something along the lines of `[0-9]{4}(-(0[1-9]|1[012])(-([0-2][0-9]|3[01]))?)?(/[0-9]{4}(-(0[1-9]|1[012])(-([0-2][0-9]|3[01]))?)?)?|Unknown`

**Comment by fxru** [comment]
fixed
