### ISSUE TITLE
"ObjectLanguageAlternativeNames" appears at the wrong place in the documentation

### ISSUE THREAD

**Issue by jblumtritt** [fxru/blam-metadata#17]
Bundle-Repository-Schema:
Element <code>ObjectLanguageAlternativeNames</code> is expected after <code>ObjectLanguageLanguageFamily</code> at the end of the Object-Language-Block.
But the documentation suggests it should be located after <code>ObjectLanguageName</code>.

**Comment by fxru** [comment]
Yes, CMDI forces an order elements before components, I changed that in the documentation now.
