### ISSUE TITLE
ObjectLanguageLanguageGenealogy does not exist in the schema

### ISSUE THREAD

**Issue by jblumtritt** [fxru/blam-metadata#18]
The Bundle-Repository-Deocumentation introduces a <code>ObjectLanguageLanguageGenealogy</code>-Element wrapping <code>ObjectLanguageLanguageFamily</code>-Elements.
But there is no such Element in the actual schema. Either the documentation or the schema should be adjusted.

**Comment by fxru** [comment]
OK, I mad the following changes:

Now a component ObjectLanguageTaxonomy contains the element(s) ObjectLanguageLanguageFamily both in the Collection as well as the Bundle profiles.

cf395a47fc7f1d2ea970a3e89aefceea538138e7
